author: Andrés M. Pérez R.
title: Musa Nocturna
email: andresmanuel.p@protonmail.com
description: >-
  Blog personal de escritura por inspiración en las noches de pensamientos vagos y café
github_username:  code-andres
twitter_username: andres_m_p_r
instagram_username: andres_m_p_r

# Build settings
theme: jekyll-theme-midnight
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

# Page
url: "https://code-andres.github.io/noctural-muse/"
paginate: 1
paginate_path: "/:num/"

# Permalink
permalink: /:title/

# google_analytics: <your-ga-id>