# Details
author: Andrés M. Pérez R.
title: Musa Nocturna
email: andresmanuel.p@protonmail.com
description: >-
  Blog personal de escritura por inspiración en las noches de pensamientos vagos y café
github_username:  code-andres
twitter_username: andres_m_p_r
instagram_username: andres_m_p_r

# Build settings
theme: jekyll-theme-midnight
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

# URL
baseurl: "/nocturnal-muse"
permalink: /:title

# Page
paginate: 1
paginate_path: "/:num"

# Categories
collections:
  category:
    output: true
    
defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"

sorted-cat:
  -
    name: Arte
    tag: arte
  -
    name: Corto
    tag: corto
  - 
    name: Medieval
    tag: Medieval
  -
    name: Motivación
    tag: motivacion
  -
    name: Vida
    tag: vida

# google_analytics: <your-ga-id>