# Welcome to Jekyll!

author: Andrés M. Pérez R.
title: Musa Nocturna
email: andresmanuel.p@protonmail.com
description: >-
  Hermosa musa de inspiración en noches tranquilas, por una mezcla de pensamientos vagos y café
twitter_username: andres_m_p_r
github_username:  code-andres

# Build settings
theme: jekyll-theme-midnight
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

baseurl: "/"
url: "/"
permalink: /:title/
markdown: kramdown
paginate: 1
paginate_path: "/:num/"
date_format: "%b %d, %Y"
show_downloads: false

# google_analytics: <your-ga-id>